#!/usr/bin/env python
import os, sys, subprocess, re

if len(sys.argv) < 2:
  print "usage: %s [additional fesvr args] <test program>" % sys.argv[0]
  sys.exit(-1)

progname = sys.argv[len(sys.argv)-1]
fesvr_args = sys.argv[1:len(sys.argv)-1]

proc = subprocess.Popen(['riscv-readelf', '-Ws', progname], stdout=subprocess.PIPE)
(pid, code) = os.waitpid(proc.pid, 0)
code == 0 or sys.exit(-1)

found_begin = False
found_end = False
for line in proc.stdout.readlines():
  if line.find('begin_signature') != -1:
    line = re.split('\s*', line)
    sig_addr = int(line[2], 16)
    found_begin = True
  elif line.find('end_signature') != -1:
    line = re.split('\s*', line)
    sig_len = int(line[2], 16)
    found_end = True

if not found_begin or not found_end:
  print "couldn't find the .test_signature section in %s" % progname

sig_len = str(sig_len - sig_addr)
sig_addr = str(sig_addr)

fesvr_args = ['fesvr'] + fesvr_args + ['-testsig', sig_addr, sig_len, progname]
proc = subprocess.Popen(fesvr_args, stdout=subprocess.PIPE)
(pid, code) = os.waitpid(proc.pid, 0)
code == 0 or sys.exit(-1)
print proc.stdout.read()
